### ISSUE TITLE
example: IEA 15MW

### ISSUE THREAD

**Issue by SeongwooCheon** [ptrbortolotti/SONATA#1]
Hi,

when I run the IEA 15MW RWT example, the error is occurred like this:

![image](https://user-images.githubusercontent.com/77769771/172654476-b6aef6b9-76f0-489f-b2a3-88f61c736974.png

And,

https://github.com/ptrbortolotti/SONATA/blob/8ae79a2a90b5ad67dc3a9bcdd22d814beb92eacc/examples/1_IEA15MW/1_sonata_IEA15.py#L51
In addition, I want to run the SONATA example for all radial stations, but the error is occurred like this:
```
Traceback (most recent call last):
  File "1_sonata_IEA15.py", line 63, in <module>
    job.blade_gen_section(topo_flag=True, mesh_flag = True, split_quads=True)  # split_quads: vabs working with False & True; anbax working with True (only)
  File "/home/default/SONATA/SONATA/classBlade.py", line 568, in blade_gen_section
    cs.cbm_gen_mesh(**kwargs)
  File "/home/default/SONATA/SONATA/cbm/classCBM.py", line 569, in cbm_gen_mesh
    self.mesh.extend(seg.mesh_layers(self.SegmentLst, global_minLen, self.WebLst, display=self.display, l0=self.refL))
  File "/home/default/SONATA/SONATA/cbm/topo/segment.py", line 351, in mesh_layers
    layer.mesh_layer(SegmentLst, global_minLen, display=display, l0=1.5 * l0)
  File "/home/default/SONATA/SONATA/cbm/topo/layer.py", line 268, in mesh_layer
    self.cells, nb_nodes = modify_sharp_corners(self.cells, self.b_BSplineLst, global_minLen, self.thickness, self.ID, proj_tol_2, alpha_crit_2, display=display)
  File "/home/default/SONATA/SONATA/cbm/mesh/mesh_improvements.py", line 127, in modify_sharp_corners
    nodeLst = [MiddleNodes[i - 1], FrontNodes[i - 1], FrontNodes[i], MiddleNodes[i]]
IndexError: list index out of range
```

How can I fix it?

**Comment by ptrbortolotti** [comment]
I've just pushed a quick fix. Unfortunately SONATA is still very fragile and we need to find the time (and funds) to make it more robust

**Comment by SeongwooCheon** [comment]
how can I reflect the change?
just command this?
`git pull`
